apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: dbvol
   namespace: testns
spec:
  accessModes:
     - ReadWriteMany
  resources:
     limits:
       storage: 3Gi
     requests:
       storage: 2Gi
  storageClassName: datapool 

---
apiVersion: v1
kind: Pod
metadata:
   name: dbpod
   namespace: testns
   labels:
     type: database
spec:
   volumes:
   - name: persvol
     persistentVolumeClaim:
        claimName: dbvol
   containers:
   - name: mysqlcon
     image: mysql:5.7
     imagePullPolicy: Always
     ports:
     - containerPort: 3306
       name: dbport
       protocol: TCP
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: pass123
     volumeMounts:
     - mountPath: /var/lib/mysql
       name: persvol
