apiVersion: v1
kind: Pod
metadata:
   name: dbpod01
   namespace: chn
   labels:
     type: database
spec:
   volumes:
   - name: nonpersvol
     emptyDir: {}
   containers:
   - name: mysqlcon
     image: mysql:5.7
     imagePullPolicy: Always
     ports:
     - containerPort: 3306
       name: dbport
       protocol: TCP
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: pass123
     volumeMounts:
     - mountPath: /var/lib/mysql
       name: nonpersvol
