apiVersion: v1
kind: PersistentVolume
metadata:
   name: testpv
   namespace: testns
spec:
  accessModes:
    - ReadWriteMany
  capacity:
     storage: 1Gi
  nfs:
   path: /pool
   server: 192.168.4.10
