apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: dbvol
   namespace: testns
spec:
  accessModes:
     - ReadWriteMany
  resources:
     limits:
       storage: 1Gi
     requests:
       storage: 900Mi
  volumeName: testpv      
