apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: httpvol
    namespace: chn
spec:
  accessModes:
     - ReadWriteMany
  resources:
     limits:
       storage: 3Gi
     requests:
       storage: 2Gi
  storageClassName: datapool
