apiVersion: v1
kind: PersistentVolume
metadata:
   name: testpv
   namespace: testns
spec:
  accessModes:
    - ReadWriteMany
  capacity:
     storage: 1Gi
  nfs:
   path: /pool
   server: 192.168.4.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: dbvol
   namespace: testns
spec:
  accessModes:
     - ReadWriteMany
  resources:
     limits:
       storage: 1Gi
     requests:
       storage: 900Mi
  volumeName: testpv

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: dbdep
   namespace: testns
spec:
  replicas: 2
  selector:
    matchLabels:
       type: db
       state: prod
  serviceName: dbsvc 
  template:
     metadata:
        name: dbpod
        namespace: testns
        labels:
          type: db
          state: prod
     spec:
       volumes:
       - name: persvol
         persistentVolumeClaim:
             claimName: dbvol
       containers:
       - image: mysql:5.7
         imagePullPolicy: Always
         name: edudb
         ports:
         - containerPort: 3306
           name: dbserver
           protocol: TCP
         resources:
             limits:
               cpu: 1
               memory: 1Gi
             requests:
               cpu: 800m
               memory: 900Mi
         env:
         - name: MYSQL_ROOT_PASSWORD
           value: pass123
         volumeMounts:
         - mountPath: /var/lib/mysql
           name: persvol


---

apiVersion: v1
kind: Service
metadata:
    name: dbsvc
    namespace: testns
spec:
  ports:
  - name: db
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
     type: db
     state: prod
